## Importar bibliotecas a usar

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

## Lectura del archivo "dataset.csv"

In [3]:
df = pd.read_csv("./dataset.csv", sep=";", dtype=str)

df.head()

,Numero Ticket,ItemID,Item,Fecha Creacion,Fecha Termino,Service Desk,Fecha Cierre,Resumen,Ubicacion,Modo Reporte,Estado,Prioridad
0,WO0000005201555,121,INODORO FLUXOMETRO,2024-05-04,06-05-24,Zona Sur,09/05/2024,REVISAR,LA FONTANA - 193054,Web HD,Cerrado,3
1,WO0000005201903,108,FOCO FLOURESCENTES,2024-05-04,05-05-24,Zona Norte,08/05/2024,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3
2,WO0000005200489,93,ESCRITORIO CERRADURA,2024-05-04,07-05-24,Zona Centro,10/05/2024,APERTURAR,TUPAC AMARU - 191038,Web HD,Cerrado,3
3,WO0000005201584,256,URINARIO FLUXOMETRO,2024-05-04,04-05-24,Zona Centro,07/05/2024,REVISAR,UNIPLAZA - 191019,Web HD,Cerrado,3
4,WO0000005201907,106,FOCO AHORRADOR,2024-05-04,05-05-24,Zona Norte,08/05/2024,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3

## Limpieza de datos

In [4]:
df = df.fillna("")

df["ItemID"] = pd.to_numeric(df['ItemID'].str.strip()).astype("Int64")
df["Fecha Creacion"] = pd.to_datetime(df["Fecha Creacion"], format='%Y-%m-%d')
df["Fecha Termino"] = pd.to_datetime(df["Fecha Termino"], format='%d-%m-%y')
df["Fecha Cierre"] = pd.to_datetime(df["Fecha Cierre"], format='%d/%m/%Y')
df["Prioridad"] = df["Prioridad"].astype(int)

In [5]:
df.head()

,Numero Ticket,ItemID,Item,Fecha Creacion,Fecha Termino,Service Desk,Fecha Cierre,Resumen,Ubicacion,Modo Reporte,Estado,Prioridad
0,WO0000005201555,121,INODORO FLUXOMETRO,2024-05-04,2024-05-06,Zona Sur,2024-05-09,REVISAR,LA FONTANA - 193054,Web HD,Cerrado,3
1,WO0000005201903,108,FOCO FLOURESCENTES,2024-05-04,2024-05-05,Zona Norte,2024-05-08,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3
2,WO0000005200489,93,ESCRITORIO CERRADURA,2024-05-04,2024-05-07,Zona Centro,2024-05-10,APERTURAR,TUPAC AMARU - 191038,Web HD,Cerrado,3
3,WO0000005201584,256,URINARIO FLUXOMETRO,2024-05-04,2024-05-04,Zona Centro,2024-05-07,REVISAR,UNIPLAZA - 191019,Web HD,Cerrado,3
4,WO0000005201907,106,FOCO AHORRADOR,2024-05-04,2024-05-05,Zona Norte,2024-05-08,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3

## Transformación de datos

In [6]:
df["Fecha Cierre"] = np.where(df["Fecha Termino"] <= df["Fecha Cierre"], df["Fecha Termino"], df["Fecha Cierre"])

df[['Agencia', 'AgenciaID']] = df['Ubicacion'].str.split('-', expand=True)
df["AgenciaID"] = df["AgenciaID"].str.strip().astype(int)
df["Agencia"] = df["Agencia"].str.strip()

In [7]:
df.head()

,Numero Ticket,ItemID,Item,Fecha Creacion,Fecha Termino,Service Desk,Fecha Cierre,Resumen,Ubicacion,Modo Reporte,Estado,Prioridad,Agencia,AgenciaID
0,WO0000005201555,121,INODORO FLUXOMETRO,2024-05-04,2024-05-06,Zona Sur,2024-05-06,REVISAR,LA FONTANA - 193054,Web HD,Cerrado,3,LA FONTANA,193054
1,WO0000005201903,108,FOCO FLOURESCENTES,2024-05-04,2024-05-05,Zona Norte,2024-05-05,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3,DIAGONAL,285003
2,WO0000005200489,93,ESCRITORIO CERRADURA,2024-05-04,2024-05-07,Zona Centro,2024-05-07,APERTURAR,TUPAC AMARU - 191038,Web HD,Cerrado,3,TUPAC AMARU,191038
3,WO0000005201584,256,URINARIO FLUXOMETRO,2024-05-04,2024-05-04,Zona Centro,2024-05-04,REVISAR,UNIPLAZA - 191019,Web HD,Cerrado,3,UNIPLAZA,191019
4,WO0000005201907,106,FOCO AHORRADOR,2024-05-04,2024-05-05,Zona Norte,2024-05-05,CAMBIAR,DIAGONAL - 285003,Web HD,Cerrado,3,DIAGONAL,285003

In [8]:
data = df[["Numero Ticket", "AgenciaID", "Agencia", "Service Desk", "Fecha Creacion", "Fecha Cierre", "Estado", "ItemID", "Item"]]
data.columns = ["numero_ticket", "agencia_id", "agencia", "service_desk", "fecha_creacion", "fecha_cierre", "estad", "item_id", "item"]